FROM node:18-alpine

WORKDIR /app

COPY sistema/backend/package*.json ./
COPY sistema/backend/src ./src
COPY sistema/backend/tsconfig.json ./

RUN npm install
RUN npm run build

ENV PORT=3001

EXPOSE 3001

CMD ["npm", "start"]
