FROM node:18-alpine

WORKDIR /app

COPY sistema/frontend/package*.json ./
COPY sistema/frontend/src ./src
COPY sistema/frontend/index.html ./
COPY sistema/frontend/vite.config.ts ./
COPY sistema/frontend/tsconfig.json ./

RUN npm install

ENV VITE_API_URL=http://backend:3001

EXPOSE 5173

CMD ["npm", "run", "dev"]
