FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY sistema/frontend ./sistema/frontend
COPY sistema/tests ./sistema/tests

RUN npm install --workspaces

ENV VITE_API_URL=http://backend:3001

EXPOSE 5173

CMD ["npm", "run", "dev", "-w", "sistema/frontend"]
